index:
    path: /
    methods: GET
    controller: App\Controller\UserController::index

sign_up:
    path: /signUp
    controller: App\Controller\UserController::register

login:
    path: /signIn
    controller: App\Controller\SecurityController::login

logout:
    path: /logout
    controller: App\Controller\SecurityController::logout

home:
    path: /home
    methods: GET
    controller: App\Controller\StorefrontController::listOrders

create_order:
    path: /order/create
    methods: GET
    controller: App\Controller\StorefrontController::create

add_order:
    path: /post/publish
    methods: POST
    controller: App\Controller\StorefrontController::publishOrder

show_order:
    path: /order/{orderId}
    methods: GET
    controller: App\Controller\StorefrontController::viewOrder

delete_order:
    path: /order/{orderId}/delete
    methods: POST
    controller: App\Controller\StorefrontController::deleteOrder